import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:path_provider/path_provider.dart';

import '../models/recording_status.dart';
import '../models/tag_name.dart';

part 'database.g.dart';

class Recordings extends Table {
  TextColumn get id => text()();
  DateTimeColumn get createdAt => dateTime()();
  IntColumn get durationMs => integer()();
  TextColumn get audioPath => text()();
  TextColumn get status => textEnum<RecordingStatus>()();
  TextColumn get transcript => text().nullable()();
  TextColumn get providerUsed => text().nullable()();
  TextColumn get errorMessage => text().nullable()();

  /// Error kind (`MikroApiException.kind.name`, or `unknown` for non-domain exceptions).
  /// Used to distinguish retriable network errors after connection restores from errors
  /// that retry cannot fix — e.g. invalid API key.
  TextColumn get errorKind => text().nullable()();

  /// Amplitude envelope of the recording: JSON array of 44 values 0..1 (see
  /// `core/audio/waveform.dart`). NULL for recordings prior to schema v3 and those
  /// where the microphone yielded no samples — the details screen then renders
  /// the card without bars rather than fabricating wave shapes.
  TextColumn get waveform => text().nullable()();

  /// Short recording title generated by the model alongside tags (see `core/api/tagging_api.dart`).
  /// NULL for recordings prior to schema v4 and those where the model returned no meaningful
  /// title — UI has its own fallback: the card displays the transcript, the header shows a generic name.
  TextColumn get title => text().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

class Tags extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text().unique()();
}

class RecordingTags extends Table {
  TextColumn get recordingId =>
      text().references(Recordings, #id, onDelete: KeyAction.cascade)();
  IntColumn get tagId => integer().references(Tags, #id, onDelete: KeyAction.cascade)();

  @override
  Set<Column> get primaryKey => {recordingId, tagId};
}

class RecordingWithTags {
  RecordingWithTags({required this.recording, required this.tags});

  final Recording recording;
  final List<String> tags;
}

@DriftDatabase(tables: [Recordings, Tags, RecordingTags])
class AppDatabase extends _$AppDatabase {
  AppDatabase()
      : super(driftDatabase(
          name: 'mikro',
          native: const DriftNativeOptions(
            databaseDirectory: getApplicationSupportDirectory,
          ),
        ));
  AppDatabase.forTesting(super.e);

  @override
  int get schemaVersion => 4;

  /// Value of the `error_kind` column for network errors — the only kind that makes sense
  /// to retry when connectivity restores. The pipeline persists this as `ApiErrorKind.network.name`,
  /// but in SQL predicates it is plain text decoupled from the enum: renaming enum constants
  /// would otherwise silently break query matching. A guard in
  /// `test/core/db/database_test.dart` verifies that both sides match.
  static const networkErrorKind = 'network';

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onUpgrade: (m, from, to) async {
          // v1 -> v2: adds errorKind. Existing rows receive NULL, so older errors
          // will not be automatically retried — we cannot know if they were network-related.
          if (from < 2) {
            await m.addColumn(recordings, recordings.errorKind);
          }
          // v2 -> v3: adds waveform. Existing recordings receive NULL because waveforms
          // were not sampled, and cannot be recreated from existing m4a files without decoding audio.
          if (from < 3) {
            await m.addColumn(recordings, recordings.waveform);
          }
          // v3 -> v4: adds title. Existing recordings receive NULL — titles are generated during
          // tagging, and already processed recordings are not resent to the model just for titles.
          if (from < 4) {
            await m.addColumn(recordings, recordings.title);
          }
        },
        beforeOpen: (details) async {
          await customStatement('PRAGMA foreign_keys = ON');
        },
      );

  Future<void> insertRecording({
    required String id,
    required DateTime createdAt,
    required int durationMs,
    required String audioPath,
    String? waveform,
  }) =>
      into(recordings).insert(RecordingsCompanion.insert(
        id: id,
        createdAt: createdAt,
        durationMs: durationMs,
        audioPath: audioPath,
        status: RecordingStatus.recorded,
        waveform: Value(waveform),
      ));

  Future<Recording?> getRecording(String id) =>
      (select(recordings)..where((r) => r.id.equals(id))).getSingleOrNull();

  /// Updates recording status. Like `errorMessage`, `errorKind` is ALWAYS overwritten — transitioning
  /// to a non-error state clears both so stale errors do not persist past resolution.
  Future<void> updateStatus(
    String id,
    RecordingStatus status, {
    String? errorMessage,
    String? errorKind,
  }) =>
      (update(recordings)..where((r) => r.id.equals(id))).write(
        RecordingsCompanion(
          status: Value(status),
          errorMessage: Value(errorMessage),
          errorKind: Value(errorKind),
        ),
      );

  /// Title is stored separately from tags: directly in the recording row, whereas tags reside in an adjacent table.
  /// `null` is a valid value — the model does not always yield a suitable display title.
  Future<void> setTitle(String id, String? title) =>
      (update(recordings)..where((r) => r.id.equals(id))).write(
        RecordingsCompanion(title: Value(title)),
      );

  Future<void> setTranscript(String id, String transcript, String providerUsed) =>
      (update(recordings)..where((r) => r.id.equals(id))).write(
        RecordingsCompanion(transcript: Value(transcript), providerUsed: Value(providerUsed)),
      );

  Future<void> setTags(String recordingId, List<String> names) => transaction(() async {
        for (final name in names) {
          await into(tags).insert(TagsCompanion.insert(name: name), mode: InsertMode.insertOrIgnore);
          final tag = await (select(tags)..where((t) => t.name.equals(name))).getSingle();
          await into(recordingTags).insert(
            RecordingTagsCompanion.insert(recordingId: recordingId, tagId: tag.id),
            mode: InsertMode.insertOrIgnore,
          );
        }
      });

  /// Appends a single tag to a recording — invoked via the "+ tag" button in details view. Name
  /// passes through [normalizeTagName], matching the normalization applied to model-generated tags.
  Future<void> addTag(String recordingId, String name) =>
      setTags(recordingId, [normalizeTagName(name)]);

  /// Removes a tag from a single recording and cleans up the tag if it has no remaining associations.
  ///
  /// Executed via typed queries rather than `customStatement`: drift does not know which tables
  /// raw SQL touches, so raw writes would fail to invalidate streams and filter chips in the library
  /// would display stale state.
  Future<void> removeTag(String recordingId, String name) => transaction(() async {
        final normalized = normalizeTagName(name);
        final tag = await (select(tags)..where((t) => t.name.equals(normalized)))
            .getSingleOrNull();
        if (tag == null) return;
        await (delete(recordingTags)
              ..where((rt) => rt.recordingId.equals(recordingId) & rt.tagId.equals(tag.id)))
            .go();
        final stillUsed =
            await (select(recordingTags)..where((rt) => rt.tagId.equals(tag.id))).get();
        if (stillUsed.isEmpty) {
          await (delete(tags)..where((t) => t.id.equals(tag.id))).go();
        }
      });

  /// Deletes a recording and cleans up orphaned tags.
  ///
  /// Raw `customStatement` is safe here ONLY because typed `delete(recordings)` runs in the same transaction:
  /// it signals to drift that the recordings table has changed, invalidating the streams.
  /// A raw customStatement alone does not invalidate anything — a stream watching only the Tags table
  /// would not receive an invalidation notification and would show deleted tags.
  Future<void> deleteRecording(String id) => transaction(() async {
        await (delete(recordings)..where((r) => r.id.equals(id))).go();
        await customStatement(
            'DELETE FROM tags WHERE id NOT IN (SELECT DISTINCT tag_id FROM recording_tags)');
      });

  /// Recordings that failed due to a network error — the only kind that makes sense to retry
  /// upon network reconnection. Auth errors or oversized files would simply fail again.
  Future<List<Recording>> networkFailedRecordings() => (select(recordings)
        ..where((r) =>
            r.status.equalsValue(RecordingStatus.error) &
            r.errorKind.equals(networkErrorKind)))
      .get();

  /// Number of recordings pending processing: in-flight plus paused due to offline status.
  Stream<int> watchQueueLength() {
    final pending = [
      RecordingStatus.recorded,
      RecordingStatus.transcribing,
      RecordingStatus.tagging,
    ];
    final query = selectOnly(recordings)
      ..addColumns([recordings.id.count()])
      ..where(recordings.status.isInValues(pending) |
          (recordings.status.equalsValue(RecordingStatus.error) &
              recordings.errorKind.equals(networkErrorKind)));
    return query.map((row) => row.read(recordings.id.count()) ?? 0).watchSingle();
  }

  Future<List<Recording>> pendingRecordings() => (select(recordings)
        ..where((r) => r.status.isInValues(
            [RecordingStatus.recorded, RecordingStatus.transcribing, RecordingStatus.tagging])))
      .get();

  Stream<List<RecordingWithTags>> watchAllWithTags() {
    final query = select(recordings).join([
      leftOuterJoin(recordingTags, recordingTags.recordingId.equalsExp(recordings.id)),
      leftOuterJoin(tags, tags.id.equalsExp(recordingTags.tagId)),
    ])
      ..orderBy([OrderingTerm.desc(recordings.createdAt)]);
    return query.watch().map((rows) {
      final byId = <String, RecordingWithTags>{};
      final order = <String>[];
      for (final row in rows) {
        final rec = row.readTable(recordings);
        final tag = row.readTableOrNull(tags);
        final entry = byId.putIfAbsent(rec.id, () {
          order.add(rec.id);
          return RecordingWithTags(recording: rec, tags: []);
        });
        if (tag != null) entry.tags.add(tag.name);
      }
      return [for (final id in order) byId[id]!];
    });
  }
}
