import 'dart:convert';

import 'package:dio/dio.dart';

import '../models/provider_config.dart';
import '../models/tag_name.dart';
import 'api_errors.dart';

/// Metadata generated by the model in a single pass: short title and tags.
///
/// The title is an optional field — `null` means "the model returned nothing displayable"
/// and is a completely valid result. The UI has its own fallback for this case, and forcing
/// a title via retry would forfeit the tags that the model returned correctly.
class RecordingMeta {
  const RecordingMeta({required this.title, required this.tags});

  final String? title;
  final List<String> tags;
}

class TaggingApi {
  TaggingApi(this._dio);

  final Dio _dio;

  static const _maxTranscriptChars = 8000;

  /// Upper limit of tags accepted FROM THE MODEL: the same number is passed to the prompt and trims
  /// the parsed result. It does not limit the recording as a whole — tags added manually
  /// in details view are saved directly to the database bypassing this path and are not capped.
  static const maxTags = 5;

  /// Upper limit of title length. Just like with tags: the number is passed to the prompt AND
  /// clamps the result, since card and panel headers are single-line rather than paragraphs.
  static const maxTitleChars = 60;

  // English prompt is deliberate. A Polish prompt biased the model toward Polish tags
  // regardless of recording language, whereas the app supports l10n — title and tag language
  // should follow the transcript, not the instruction language.
  static const _systemPrompt =
      'You label a transcript of a voice note. Return ONLY a JSON object with '
      'exactly two keys: "title" and "tags", both written in the same language '
      'as the transcript. "title" is a short specific headline for this '
      'recording, at most $maxTitleChars characters, naming what the recording '
      'is actually about. "tags" is an array of at most $maxTags short tags '
      '(1-3 words each), lowercase. Tag only what the recording is '
      'specifically about: concrete topics, proper names, projects, people, '
      'places, events, technical terms. Never return generic labels or titles '
      'that would fit any recording whatsoever, such as "note", "recording", '
      '"conversation", "audio", "voice", "thoughts", or their equivalents in '
      'the language of the transcript. Fewer sharp tags beat filling the '
      'limit; return an empty array when the transcript contains nothing '
      'specific. No other text.';

  Future<RecordingMeta> generateMeta(
      {required String transcript, required ProviderConfig config}) async {
    for (var attempt = 0; attempt < 2; attempt++) {
      final content = await _chat(transcript, config);
      final meta = parseMeta(content);
      if (meta != null) return meta;
    }
    throw MikroApiException(ApiErrorKind.badTags, 'meta object unparsable');
  }

  Future<String> _chat(String transcript, ProviderConfig config) async {
    final clipped = transcript.length > _maxTranscriptChars
        ? transcript.substring(0, _maxTranscriptChars)
        : transcript;
    try {
      final response = await _dio.post<dynamic>(
        '${config.baseUrl}/chat/completions',
        data: {
          'model': config.tagModel,
          'temperature': 0,
          'messages': [
            {'role': 'system', 'content': _systemPrompt},
            {'role': 'user', 'content': clipped},
          ],
        },
        options: Options(headers: {'Authorization': 'Bearer ${config.apiKey}'}),
      );
      // Type casting and descending the structure is done step by step explicitly. The chain
      // data?['choices']?[0]?['message']?['content'] produced raw runtime errors:
      // RangeError on empty choices list and _TypeError on any unexpected shape,
      // while the generic post<Map<String, dynamic>> turned non-map bodies into false network errors.
      final data = response.data;
      if (data is! Map<String, dynamic>) {
        throw MikroApiException(ApiErrorKind.badFormat, 'response body is not an object');
      }
      final content = _extractContent(data);
      if (content is! String) {
        throw MikroApiException(ApiErrorKind.noContent, 'no message content in response');
      }
      return content;
    } on DioException catch (e) {
      throw mapDioError(e);
    }
  }

  /// Navigates `choices[0].message.content` without assuming anything about the response structure.
  /// Returns null for any structure not conforming to the contract.
  static Object? _extractContent(Map<String, dynamic> data) {
    final choices = data['choices'];
    if (choices is! List || choices.isEmpty) return null;
    final choice = choices.first;
    if (choice is! Map) return null;
    final message = choice['message'];
    if (message is! Map) return null;
    return message['content'];
  }

  /// Extracts the `{"title": ..., "tags": [...]}` object from model output.
  ///
  /// `null` means "this response cannot be used" and triggers a retry. This also applies
  /// to a plain tags array — valid up to schema v4, but now considered malformed output
  /// because it would silently drop the title.
  static RecordingMeta? parseMeta(String content) {
    var s = content.trim();
    final fence = RegExp(r'^```[a-z]*\s*([\s\S]*?)\s*```$').firstMatch(s);
    if (fence != null) s = fence.group(1)!.trim();
    final start = s.indexOf('{');
    final end = s.lastIndexOf('}');
    if (start == -1 || end <= start) return null;
    try {
      final decoded = jsonDecode(s.substring(start, end + 1));
      if (decoded is! Map) return null;
      final tags = _parseTags(decoded['tags']);
      if (tags == null) return null;
      return RecordingMeta(title: _parseTitle(decoded['title']), tags: tags);
    } on FormatException {
      return null;
    }
  }

  /// We enforce [maxTags] limit here, not just in the prompt: prompt is a request that the model
  /// might ignore, and the pipeline saves everything it receives to the database.
  static List<String>? _parseTags(Object? raw) {
    if (raw is! List) return null;
    // Empty [] is an intentional "nothing specific here" answer and proceeds without retry.
    // A list that only becomes empty after filtering junk is malformed model output — null,
    // which triggers a second attempt. These two paths must not be conflated.
    if (raw.isEmpty) return const [];
    final tags = raw
        .whereType<String>()
        .map(normalizeTagName)
        .where((t) => t.isNotEmpty)
        .toSet()
        .take(maxTags)
        .toList();
    return tags.isEmpty ? null : tags;
  }

  /// Clamps title to a single line and up to [maxTitleChars] characters. Missing title is not an error,
  /// so any unrenderable shape resolves to `null` — not a retry.
  static String? _parseTitle(Object? raw) {
    if (raw is! String) return null;
    final oneLine = raw.replaceAll(RegExp(r'\s+'), ' ').trim();
    if (oneLine.isEmpty) return null;
    if (oneLine.length <= maxTitleChars) return oneLine;
    return oneLine.substring(0, maxTitleChars).trimRight();
  }
}
